# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_master', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OccupationCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.OccupationCode')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1000)),
                ('onet_id', models.DecimalField(decimal_places=0, max_digits=8)),
                ('updated_at', models.DateField()),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Occupation')),
            ],
        ),
        migrations.AddField(
            model_name='occupation',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.OccupationCode'),
        ),
        migrations.AlterUniqueTogether(
            name='occupation',
            unique_together=set([('code', 'is_master')]),
        ),
    ]
