# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_seed_initial_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='is_master',
            field=models.NullBooleanField(),
        ),
    ]
