# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_auto_20170604_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
