# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_auto_20170604_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='occupation',
        ),
        migrations.AddField(
            model_name='task',
            name='occupation_code',
            field=models.ForeignKey(default='bubba', on_delete=django.db.models.deletion.CASCADE, to='resume_builder.OccupationCode'),
            preserve_default=False,
        ),
    ]
