# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0008_auto_20170604_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='onet_id',
            field=models.DecimalField(decimal_places=0, max_digits=8, unique=True),
        ),
    ]
