# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:45
from __future__ import unicode_literals

import csv
import os
from datetime import datetime

from django.db import migrations

DB_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'onet_db_21.3')


def _get_models(apps):
    return (apps.get_model('resume_builder', 'OccupationCode'),
            apps.get_model('resume_builder', 'Occupation'),
            apps.get_model('resume_builder', 'OccupationDescription'),
            apps.get_model('resume_builder', 'Task'))


def forwards_func(apps, schema_editor):
    OccupationCode, Occupation, OccupationDescription, Task = _get_models(apps)

    # Load and parse the occupation data TSV export
    with (open(os.path.join(DB_DIR, 'Occupation Data.tsv'))) as tsv:
        reader = csv.reader(tsv, delimiter='\t')

        for row in reader:
            code = OccupationCode(code=row[0])
            code.save()
            Occupation(code=code, name=row[1], is_master=True).save()
            OccupationDescription(code=code, description=row[2]).save()

    # Load and parse the occupation alternate titles
    with (open(os.path.join(DB_DIR, 'Alternate Titles.tsv'))) as tsv:
        reader = csv.reader(tsv, delimiter='\t')

        for row in reader:
            Occupation(code_id=row[0], name=row[1]).save()

    # Load and parse the tasks
    with (open(os.path.join(DB_DIR, 'Task Statements.tsv'))) as tsv:
        reader = csv.reader(tsv, delimiter='\t')

        for row in reader:
            date = datetime.strptime(row[5], '%m/%Y')
            Task(occupation_code_id=row[0], onet_id=row[1], task=row[2], updated_at=date).save()


def reverse_func(apps, schema_editor):
    OccupationCode, Occupation, OccupationDescription, Task = _get_models(apps)

    OccupationCode.objects.all().delete()
    Occupation.objects.all().delete()
    OccupationDescription.objects.all().delete()
    Task.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0009_auto_20170604_0544'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
