# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 06:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resume_builder', '0011_auto_20170604_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.PositiveSmallIntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('objective', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('occupation_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
                ('occupation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Occupation')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOccupationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=1000)),
                ('resume_occupation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.ResumeOccupation')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField(max_length=500)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTypeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume')),
            ],
        ),
        migrations.DeleteModel(
            name='ResumeExport',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='device_type_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='zip_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='resume',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       to='resume_builder.Resume'),
            preserve_default=False,
        ),
    ]
