# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resume_builder', '0013_auto_20170609_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetyperesponse',
            name='occupation_gap',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetyperesponse',
            name='occupation_history',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetyperesponse',
            name='occupation_seeking',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
